DjangoFinancial/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('financial.urls')),
    url(r'^customer/$', include('financial.urls')),
    url(r'^customer/(\d+)/$', include('financial.urls')),
    url(r'^customer/(\d+)/s/(\d+)/$', include('financial.urls')),
    url(r'^customer/(\d+)/c/(\d+)/$', include('financial.urls')),


]

financial/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'customers', views.CustomerViewSet)
router.register(r'stocks', views.StockViewSet)
router.register(r'cryptos', views.CryptoViewSet)

urlpatterns = [
    url(r'^$', views.index, name='mainpage'),
    url(r'^customer/$', views.allCustomers, name='allcustomers'),
    url(r'^customer/(\d+)/$', views.oneCustomer, name='onecustomer'),
    url(r'^customer/(\d+)/s/(\d+)/$', views.stockView, name='stockview'),
    url(r'^customer/(\d+)/c/(\d+)/$', views.cryptoView, name='cryptoview'),
    url(r'api/', include(router.urls)),
    url(r'^customer/(\d+)/update', views.customerEdit, name='customerupdate'),
    url(r'^customer/(\d+)/s/(\d+)/update', views.stockEdit, name='stockupdate'),
    url(r'^customer/(\d+)/c/(\d+)/update', views.cryptoEdit, name='cryptoupdate'),
    url(r'^topten/(\d+)/', views.topTen, name='topten'),
    url(r'^customer/(\d+)/s/(\d+)/delete', views.stockDelete, name='stockdelete'),
    url(r'^customer/(\d+)/c/(\d+)/delete', views.cryptoDelete, name='cryptodelete'),
    url(r'^customer/(\d+)/delete', views.customerDelete, name='customerdelete'),
    ]

financial/models.py
from django.db import models
from datetime import date


class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    zip = models.DecimalField(max_digits=5, decimal_places=0)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=12)

    def __str__(self):
        return self.name


class Stock(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    symbol = models.CharField(max_length=6)
    name = models.CharField(max_length=30)
    numShares = models.DecimalField(max_digits=10, decimal_places=0)
    buyPrice = models.DecimalField(max_digits=10, decimal_places=2)
    buyDate = models.DateField(default=date.today())


class Crypto(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE)
    symbol = models.CharField(max_length=6)
    name = models.CharField(max_length=30)
    numCoins = models.DecimalField(max_digits=15, decimal_places=4)
    buyPrice = models.DecimalField(max_digits=7, decimal_places=2)
    buyDate = models.DateField(default=date.today())


class TopTen(models.Model):
    symbol = models.CharField(max_length=6)
    name = models.CharField(max_length=30)

financial/forms.py
from django import forms
from .models import Customer, Crypto, Stock

class EditCustomerForm(forms.ModelForm):
    name = forms.CharField(max_length=50)
    address = forms.CharField(max_length=50)
    city = forms.CharField(max_length=30)
    state = forms.CharField(max_length=30)
    zip = forms.DecimalField(max_digits=5, decimal_places=0)
    email = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=12)

    class Meta:
        model = Customer
        fields = ['name', 'address', 'city', 'state', 'zip', 'email', 'phone']


class EditStockForm(forms.ModelForm):
    symbol = forms.CharField(max_length=6)
    name = forms.CharField(max_length=30)
    numShares = forms.DecimalField(max_digits=10, decimal_places=0)
    buyPrice = forms.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        model = Stock
        fields = ['symbol', 'name', 'numShares', 'buyPrice']


class EditCryptoForm(forms.ModelForm):
    symbol = forms.CharField(max_length=6)
    name = forms.CharField(max_length=30)
    numCoins = forms.DecimalField(max_digits=15, decimal_places=4)
    buyPrice = forms.DecimalField(max_digits=7, decimal_places=2)

    class Meta:
        model = Crypto
        fields = ['symbol', 'name', 'numCoins', 'buyPrice']


class DeleteCryptoForm(forms.ModelForm):
    class Meta:
        model = Crypto
        fields = []


class DeleteStockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = []


class DeleteCustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = []

financial/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Customer, Stock, Crypto, TopTen
from rest_framework import viewsets
from .serializers import CustomerSerializer, StockSerializer, CryptoSerializer
from .services import get_stock_price, get_crypto_price
from django import forms
from .forms import EditCustomerForm, EditStockForm, EditCryptoForm, DeleteCryptoForm, DeleteCustomerForm, DeleteStockForm


def index(request):
    return render(request, 'financial/index.html')


def allCustomers(request):
    customer = Customer.objects.all
    return render(request, 'financial/customer.html', {'customer': customer})


def oneCustomer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    return render(request, 'financial/oneCustomer.html', {'customer': customer})


def stockView(request, customer_id, stock_id):
    stock = get_object_or_404(Stock, pk=stock_id)
    stock.currentPrice = get_stock_price(stock.symbol)
    return render(request, 'financial/stock.html', {'stock': stock})


def cryptoView(request, customer_id, crypto_id):
    crypto = get_object_or_404(Crypto, pk=crypto_id)
    crypto.currentPrice = get_crypto_price(crypto.symbol)
    return render(request, 'financial/crypto.html', {'crypto': crypto})

class CustomerViewSet(viewsets.ModelViewSet):
    queryset = Customer.objects.all()
    serializer_class = CustomerSerializer

class StockViewSet(viewsets.ModelViewSet):
    queryset = Stock.objects.all()
    serializer_class = StockSerializer

class CryptoViewSet(viewsets.ModelViewSet):
    queryset = Crypto.objects.all()
    serializer_class = CryptoSerializer

def customerEdit(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == "POST":
        form = EditCustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save()
            return redirect(f'/customer/{customer_id}', pk=customer_id)
    else:
        form = EditCustomerForm(instance=customer)
    return render(request, 'financial/update_form.html', {'form': form})


def customerDelete(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    if request.method == "POST":
        form = DeleteCustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer.delete()
            return redirect(f'/customer/', pk=customer_id)
    else:
        form = EditCustomerForm(instance=customer)
    return render(request, 'financial/delete_form.html', {'form': form})


def stockEdit(request, customer_id, stock_id):
    stock = get_object_or_404(Stock, pk=stock_id)
    if request.method == "POST":
        form = EditStockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save()
            return redirect(f'/customer/{customer_id}')
    else:
        form = EditStockForm(instance=stock)
    return render(request, 'financial/update_form.html', {'form': form})

def stockDelete(request, customer_id, stock_id):
    stock = get_object_or_404(Stock, pk=stock_id)
    if request.method == "POST":
        form = DeleteStockForm(request.POST, instance=stock)
        if form.is_valid():
            stock.delete()
            return redirect(f'/customer/{customer_id}')
    else:
        form = DeleteStockForm(instance=stock)
    return render(request, 'financial/delete_form.html', {'form': form})


def cryptoDelete(request, customer_id, crypto_id):
    crypto = get_object_or_404(Crypto, pk=crypto_id)
    if request.method == "POST":
        form = DeleteCryptoForm(request.POST, instance=crypto)
        if form.is_valid():
            crypto.delete()
            return redirect(f'/customer/{customer_id}')
    else:
        form = DeleteCryptoForm(instance=crypto)
    return render(request, 'financial/delete_form.html', {'form': form})


def cryptoEdit(request, customer_id, crypto_id):
    crypto = get_object_or_404(Crypto, pk=crypto_id)
    if request.method == "POST":
        form = EditCryptoForm(request.POST, instance=crypto)
        if form.is_valid():
            form = form.save()
            return redirect(f'/customer/{customer_id}')
    else:
        form = EditCryptoForm(instance=crypto)
    return render(request, 'financial/update_form.html', {'form': form})

def topTen(request, topten_id):
    topten = get_object_or_404(TopTen, pk=topten_id)
    topten.currentPrice1 = get_stock_price('AAPL')
    topten.symbol1 = 'AAPL'
    topten.name1 = 'Apple'
    topten.currentPrice2 = get_stock_price('GOOG')
    topten.symbol2 = 'GOOG'
    topten.name2 = 'Google'
    topten.currentPrice3 = get_stock_price('TSLA')
    topten.symbol3 = 'TSLA'
    topten.name3 = 'Tesla'
    topten.currentPrice4 = get_stock_price('MSFT')
    topten.symbol4 = 'MSFT'
    topten.name4 = 'Microsoft'
    topten.currentPrice5 = get_stock_price('AMZN')
    topten.symbol5 = 'AMZN'
    topten.name5 = 'Amazon'
    topten.currentPrice6 = get_crypto_price('BTC')
    topten.symbol6 = 'BTC'
    topten.name6 = 'Bitcoin'
    topten.currentPrice7 = get_crypto_price('ETH')
    topten.symbol7 = 'ETH'
    topten.name7 = 'Ethereum'
    topten.currentPrice8 = get_crypto_price('XRP')
    topten.symbol8 = 'XRP'
    topten.name8 = 'Ripple'
    topten.currentPrice9 = get_crypto_price('BCH')
    topten.name9 = 'Bitcoin Cash'
    topten.symbol9 = 'BCH'
    topten.currentPrice10 = get_crypto_price('LTC')
    topten.symbol10 = 'LTC'
    topten.name10 = 'Litecoin'
    return render(request, 'financial/topten.html', {'topten': topten})

financial/templates/financial/crypto.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{ crypto.name }}</title>
  </head>
  <body>
     <div class ="jumbotron text-center">
        <h1><b>{{ crypto.customer.name }}'s {{ crypto.name }}</b></h1>
    </div>
     <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Name</th>
                        <th>Number of Units</th>
                        <th>Buy Price</th>
                        <th>Current Price</th>
                        <th>Date Bought</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    <tr>
                        <td>{{ crypto.name }}({{ crypto.symbol }})</td>
                        <td>{{ crypto.numCoins }}</td>
                        <td>${{ crypto.buyPrice}}</td>
                        <td>${{ crypto.currentPrice }}</td>
                        <td>{{ crypto.buyDate }}</td>
                        <td><a href='update/'>Edit</a></td>
                        <td><a href='delete/'>Delete</a></td>
                    </tr>
                </table>
            </div>
        </div>
     </div>

         <div class="container">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/customer/">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/financial/customer/">Advisors</a>
            </li>
        </ul>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

financial/templates/financial/customer.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Customer List</title>
  </head>
  <body>
    <div class ="jumbotron text-left">
        <h1><b>DP's Django Financial</b></h1>
    </div>
    <h2>Customer List</h2>
    <ul>
        {%  for customer in customer %}
            <li><a href="{% url 'onecustomer' customer.id %}">{{ customer.name }}</a> - {{ customer.city }}</li>
        {% endfor %}
    </ul>

         <div class="container">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/customer/">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/financial/customer/">Advisors</a>
            </li>
        </ul>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

financial/templates/financial/delete_form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <div class ="jumbotron text-left">
        <h1><b>Please Confirm Deletion</b></h1>
          <p>This cannot be undone</p>
      </div>

      <form action="" method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Delete" />
      </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

financial/templates/financial/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>DP's Django Financial</title>
  </head>
  <body>
    <div class ="jumbotron text-center">
        <h1><b>Welcome to DP's Django Financial</b></h1>
        <button type="button" class="btn btn-dark" onclick="location.href = 'https://i.imgur.com/HikzcqA.jpg';">Enjoy!</button>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h3>Customers</h3>
                <button type="button" class="btn btn-primary" onclick="location.href = '/customer/';">View Customers</button>
                <button type="button" class="btn btn-primary" onclick="location.href = '/api/';">View API</button>
        </div>
            <div class="col-sm-4">
                <h3>Advisors</h3>
                <button type="button" class="btn btn-primary" onclick="location.href = '/admin/financial/customer/';">View Advisor Portal</button>
        </div>
            <div class="col-sm-4">
                <h3>Top Ten Investments</h3>
                <button type="button" class="btn btn-primary" onclick="location.href = '/topten/1';">View</button>
            </div>
        </div>
    </div>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

financial/templates/financial/oneCustomer.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{{ customer.name }}</title>
  </head>
  <body>
    <div class ="jumbotron text-center">
        <h1><b>{{ customer.name }}'s Portfolio</b></h1>
        <p><a href="./update/">Edit</a> <a href="./delete/"> Delete</a></p>
    </div>
     <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h3>Stocks</h3>
                <table class="table">
                    <tr>
                        <th>Stock</th>
                        <th>Shares</th>
                        <th>Buy Price</th>
                        <th></th>
                    </tr>
                    {%  for stock in customer.stock_set.all %}
                    <tr>
                        <td><a href="../{{ stock.customer.id }}/s/{{ stock.id }}">{{ stock.symbol }}</a></td>
                        <td>{{ stock.numShares }}</td>
                        <td>{{ stock.buyPrice }}</td>
                        <td><a href="../{{ stock.customer.id }}/s/{{ stock.id }}/update">Update</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-sm-4">
                <h3>Cryptos</h3>
                <table class="table">
                    <tr>
                        <th>Crypto</th>
                        <th>Units</th>
                        <th>Buy Price</th>
                        <th></th>
                    </tr>
                    {%  for crypto in customer.crypto_set.all %}
                    <tr>
                        <td><a href="../{{ crypto.customer.id }}/c/{{ crypto.id }}">{{ crypto.symbol }}</a></td>
                        <td>{{ crypto.numCoins }}</td>
                        <td>{{ crypto.buyPrice }}</td>
                        <td><a href="../{{ crypto.customer.id }}/c/{{ crypto.id }}/update">Update</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-sm-4">
                <h3>Top Ten Investments</h3>
                <button type="button" class="btn btn-primary" onclick="location.href = 'http://127.0.0.1:8000/topten/1';">View</button>
            </div>
    </div>

         <div class="container">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/customer/">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/financial/customer/">Advisors</a>
            </li>
        </ul>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

financial/templates/financial/stock.html
<!doctype html>
<html lang="en">
{% load staticfiles %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <title>{{ stock.name }}</title>
  </head>
  <body>
    <div class ="jumbotron text-center">
        <h1><b>{{ stock.customer.name }}'s {{ stock.name }} Stock</b></h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <table class="table table-bordered text-center">
                    <tr>
                        <th>Name</th>
                        <th>Number of Shares</th>
                        <th>Buy Price</th>
                        <th>Current Price</th>
                        <th>Date Bought</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    <tr>
                        <td>{{ stock.name }}({{ stock.symbol }})</td>
                        <td>{{ stock.numShares }}</td>
                        <td>{{ stock.buyPrice}}</td>
                        <td>{{ stock.currentPrice }}</td>
                        <td>{{ stock.buyDate }}</td>
                        <td><a href='update/'>Edit</a></td>
                        <td><a href='delete/'>Delete</a></td>
                    </tr>
                </table>
            </div>
        </div>
     </div>

          <div class="container">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/customer/">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/admin/financial/customer/">Advisors</a>
            </li>
        </ul>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>